# Generated by Django 4.2.5 on 2024-03-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_video_video_file_alter_video_video_file1080p_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
